CREATE DATABASE SRUDENT1
USE SRUDENT1

CREATE TABLE STUDENT1(ID INT,NAME VARCHAR(10),AGE TINYINT,SALARY MONEY)
--SP_HELP STUDENT1--  --VIEWING THE TABLE STRUCTURE--
SELECT * FROM STUDENT1
ALTER TABLE STUDENT1 ALTER COLUMN NAME VARCHAR(50);  --CHNAGE THE SIZE OF DATA TYPE--
ALTER TABLE STUDENT1 ADD ADDRESS VARCHAR(70)         --ADD ONE NEW COUMN TO THE TABLE--
ALTER TABLE STUDENT1 DROP COLUMN AGE			     --DROP THE COLUMN IN A TABLE
--SP_RENAME 'STUDENT1','STUDENT'						 --CHANGE THE TABLE NAME--
--SP_RENAME 'STUDENT1.ADDRESS','EADDRESS';            --CHANGE THE COLOUMN NAME IN TABLE--
TRUNCATE TABLE STUDENT1




